### ISSUE TITLE
Resources consumption

### ISSUE THREAD

**Issue by eugene2005** [djanosik/Moon.Localization#1]
The main problem about this library is that it reloads ALL resources every time client makes an http request. For example if there 10 localization resources (file with translations) and 100 clients hitting server at the same time it will result in 1000 file reads on the server where in fact it needs to be done only 10 times at max.

**Comment by djanosik** [comment]
Well, you are right! It's stupid to load dictionaries on every request. It should be fixed now. Thank you!
