### ISSUE TITLE
Moon.Localization upgrade to RC1-end

### ISSUE THREAD

**Issue by CamiloBernal** [djanosik/Moon.Localization#2]
Hi, thanks for sharing this great resource. I have a question: Do you have an update planned for "ASPNet 5 Rc1-end"? if so, how soon they are scheduled approximately ?.

Thank you

Camilo

**Comment by djanosik** [comment]
Hi,

thank you! I will update all my libs tomorrow.

BTW: Why did you choose my localization library over the one from ASP.NET team?

Dusan

**Comment by CamiloBernal** [comment]
Hello,
Thanks, I chose Moon.Localization because the location of  AspNet 5 at the moment is a complete mess. Resources do not work well, require more work, it is not easy to understand and very little documentation.

**Comment by djanosik** [comment]
Ok :) The library should work with DNX RC1 without any issues.
