### ISSUE TITLE
Switch language?

### ISSUE THREAD

**Issue by cindro** [djanosik/Moon.Localization#3]
I love this library, I just have below question.

I have en.json and fr.json, everything works fine.

1.  What is the best way to switch to a different language from a Controller Action?

2. In startup.cs, what is the best way to choose a default language?

**Comment by cindro** [comment]
2. I know this works for startup.cs but not sure if that is the suggested way?

app.UseLocalization(r => r.LoadJson("resources")).UseRequestLocalization(new RequestCulture("en"))

**Comment by djanosik** [comment]
1. You can set the `Current-Culture` cookie wherever you want (in an action method, in JavaScript, etc.). See `GetRequestCulture` in [CultureMiddleware.cs](https://github.com/djanosik/Moon.Localization/blob/master/src/Moon.AspNet.Localization/Middlewares/CultureMiddleware.cs). The `UseRequestLocalization` method will not work.

2. You can set `Resources.DefaultCulture`. I will add an overload of `UseLocalization` method accepting the default culture as a parameter.

**Comment by cindro** [comment]
@djanosik Seriously, your library is the best, THANK YOU sir.
