### ISSUE TITLE
Core RC2 Support?

### ISSUE THREAD

**Issue by cindro** [djanosik/Moon.Localization#4]
Thank you for this great package, the best localization package in my opinion.

Is it possible to publish a version that supports the RC2 release?

RC2 upgraded to Microsoft.AspNetCore.Builder

**Comment by djanosik** [comment]
I might update all my libs next week :) I am thinking about integrating Moon.Localization with ASP.NET Core localization.

**Comment by cindro** [comment]
Sounds interesting, what I love about this library is its simplicity...I can just store all the data in a json file and return values easily.

**Comment by cindro** [comment]
Don't want to trouble you but when can we expect an update? I prefer this library over Microsoft's.

**Comment by djanosik** [comment]
There are some dependencies I can't upgrade right now. I need to wait for .NET Core RTM and Preview 2 of tooling.

**Comment by cindro** [comment]
Thank you.

**Comment by djanosik** [comment]
Version [2.1.3](https://www.nuget.org/packages/Moon.AspNetCore.Localization/2.1.3) should be fully compatible with RC2.
